# Generated by Django 4.0.3 on 2022-03-17 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill_check', '0002_subject_remove_skills_name_skills_subject_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='subject_name',
        ),
    ]
