# Generated by Django 4.0.3 on 2022-03-17 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill_check', '0003_remove_skills_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='subject_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skill_check.subject'),
        ),
    ]
