# Generated by Django 4.0.3 on 2022-03-17 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill_check', '0004_skills_subject_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='subject_name',
            new_name='subject',
        ),
    ]
